name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dockerfile Linter
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile


    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
